run:
  timeout: 2m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive
    - gocritic
    - ineffassign
    - typecheck
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocyclo
    - dupl
    - dogsled
    - exportloopref
    - goconst
    - gocognit
    - godot
    - godox
    - nolintlint
    - whitespace
    - forbidigo
    - forbidigo
    - lll
    - stylecheck
    - gosec
    - asasalint
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - goerr113
    - gomnd
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - nestif
    - noctx
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - thelper
    - tparallel
    - wastedassign
    - zerologlint
  disables:
    - wrapcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120 